# Generated by Django 4.0.1 on 2022-04-22 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Созданa')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Созданa')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Store.product')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Store.propertytype')),
            ],
        ),
    ]
