# Generated by Django 4.0.1 on 2022-04-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_propertytype_propertyvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyvalue',
            name='value',
            field=models.CharField(max_length=1000, verbose_name='Значение'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyvalue',
            unique_together={('property_type', 'value')},
        ),
    ]
