# Generated by Django 4.0.1 on 2022-04-22 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_propertyvalue_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyvalue',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='Store.product'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_type_of_value', to='Store.propertytype'),
        ),
    ]
